apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: deploy-elearning
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: eks-app
          image: educative1/deploy-eks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80